#pragma once

#define MOTOR_RIGHT_GPIO_PIN1 18
#define MOTOR_RIGHT_GPIO_PIN2 19
#define MOTOR_RIGHT_PWM_PIN 5
#define GPIO_PIN_SPEED_RA 12
#define GPIO_PIN_SPEED_RB 14
// #define GPIO_PIN_SPEED_RA 27
// #define GPIO_PIN_SPEED_RB 26

#define MOTOR_LEFT_GPIO_PIN1 32
#define MOTOR_LEFT_GPIO_PIN2 33
#define MOTOR_LEFT_PWM_PIN 25
#define GPIO_PIN_SPEED_LA 27
#define GPIO_PIN_SPEED_LB 26
// #define GPIO_PIN_SPEED_LA 12
// #define GPIO_PIN_SPEED_LB 14

#define Console Serial